version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:30"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers: [ryanjwilke]
  assignees: [ryanjwilke]
  labels: [dependencies]
  versioning-strategy: increase
